# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
#测试类
#用例五要素，标题，前置，步骤，预期，实际
#关于调试定位元素，可以装一个 chrome的插件叫 chropathhttps://chrome.google.com/webstore/detail/chropath/ljngjbnaijcbncmcnjfhigebomdlkcjo 好用max
class TestLagou():
  #用例执行之前的操作
  def setup_method(self, method):
    #自动导包 alt+enter
    self.driver = webdriver.Chrome()
    self.vars = {}
  #用例执行之后的操作
  def wait_for_window(self, timeout = 2):
    #window等待操作
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  def teardown_method(self, method):
    self.driver.quit()
  def test_lagou(self):
    self.driver.get("https://www.lagou.com/")
    self.driver.set_window_size(1280, 768)
    #先等一下弹窗
    time.sleep(2)
    #X掉弹窗
    self.driver.find_element(By.ID, "cboxClose").click()
    #X掉之后等待准备搜索一下
    time.sleep(2)
    #定位方式，具体id定位信息，搜索职位，关于各类定位可以 参考下：https://juejin.cn/post/7074779332819812389#heading-12 常用的什么id，xpath
    self.driver.find_element(By.ID, "search_input").click()
    self.driver.find_element(By.ID, "search_input").send_keys("字节跳动")
    self.driver.find_element(By.ID, "search_button").click()
    #获取主页的字节跳动公司的卡片
    time.sleep(5)
    res=self.driver.find_element(By.CSS_SELECTOR, ".company-card__1BXKp h3")
    #输出实际的结果
    print(res.text)
    #实际和预期判断
    assert "字节跳动"==res.text

    self.driver.find_element(By.ID, "keyword").click()
    #模拟双击,再单击选中全部模拟下清空内容
    element = self.driver.find_element(By.ID, "keyword")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    actions.click(element).perform()
    #变成搜索阿里巴巴
    self.driver.find_element(By.ID, "keyword").send_keys("阿里巴巴")
    self.driver.find_element(By.ID, "keyword").send_keys(Keys.ENTER)
    time.sleep(3)
    #点击进入阿里的主页按钮，用css选择器去定位
    self.driver.find_element(By.CSS_SELECTOR, ".c-btn__uA18z i").click()
    time.sleep(3)
    #要切换下window
    self.vars["window_handles"] = self.driver.window_handles
    self.vars["win2984"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win2984"])
    #用xpath定位公司标题开头阿里巴巴集团确认是否符合
    res2 = self.driver.find_element(By.XPATH, "/html[1]/body[1]/div[6]/div[1]/div[1]/div[1]/h1[1]/a[1]")
    # 输出实际的结果
    print(res2.text)
    # 实际和预期判断
    assert "阿里巴巴集团" == res2.text
  '''''''''
  def test_ali(self):
    self.driver.get("https://www.lagou.com/gongsi/v1/450553c4629f55670cb76ed9ce9731d844a07ad3e4ddf579.html")
    time.sleep(3)
    res2 = self.driver.find_element(By.XPATH, "/html[1]/body[1]/div[6]/div[1]/div[1]/div[1]/h1[1]/a[1]")
    print(res2.text)
  
  '''''''''